from os import getenv

HOST_UMBLER = getenv("HOST_UMBLER")
PORT_UMBLER = getenv("PORT_UMBLER")
USER_UMBLER = getenv("USER_UMBLER")
PASS_UMBLER = getenv("PASS_UMBLER")

PROD_MONGO_URI = getenv("PROD_MONGO_URI")
DEV_MONGO_URI = getenv("DEV_MONGO_URI")
